#!/usr/bin/env bash
# Script for resetting the database, extracting the bugs from
# phpbugtracker on trevor, and importing them into midge.

MIDGE_PATH=$(pwd)/../bin/

sudo bash <<EOF
  cd ${MIDGE_PATH}
  source setup-paths.sh
  midge-admin teardown
  midge-admin setup
EOF

scp phpbt_extract.py trevor:
ssh trevor python phpbt_extract.py
scp trevor:{users.txt,bugs.txt,comments.txt} .

python importer.py